// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'


declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('@/components/Icon/src/Icon.vue')['default']
    IconSelect: typeof import('@/components/Icon/src/IconSelect.vue')['default']
  }
}